// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Image: typeof import('primevue/image')['default']
    InputText: typeof import('primevue/inputtext')['default']
    IPrimeCircleFill: typeof import('~icons/prime/circle-fill')['default']
    Knob: typeof import('primevue/knob')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    NavBar: typeof import('./../views/components/NavBar.vue')['default']
    Paginator: typeof import('primevue/paginator')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Slider: typeof import('primevue/slider')['default']
    SpeedDial: typeof import('primevue/speeddial')['default']
    TabMenu: typeof import('primevue/tabmenu')['default']
    TheFooter: typeof import('./../views/components/TheFooter.vue')['default']
    TheHeader: typeof import('./../views/components/TheHeader.vue')['default']
  }
}
