// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Chart: typeof import('primevue/chart')['default']
    Column: typeof import('primevue/column')['default']
    CreditCard: typeof import('./../views/components/CreditCard.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Image: typeof import('primevue/image')['default']
    NavBar: typeof import('./../views/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabMenu: typeof import('primevue/tabmenu')['default']
    TheFooter: typeof import('./../views/components/TheFooter.vue')['default']
    TheHeader: typeof import('./../views/components/TheHeader.vue')['default']
  }
}
